name: ci-cd rev

on:
  push:

jobs:
  docker:
     runs-on: ubuntu-latest

     steps:
       - name: check actions
         uses: actions/checkout@v4

       - name: Dockerhub login
         run: |
          echo "${{secrets.DOCKER_PASSWORD}}"| \
          docker login -u "sruthidoc07" --password-stdin

       - name: Docker build image
        run: |
         docker build -t sruthidoc07/web:v1 .

       - name: push docker image
        run:  |
         docker push sruthidoc07/web:v1

